config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    validates :color, inclusion: { in: %w(White Black Red Blue Orange Green),
      message: "%{value} is not a valid color" }
    validates :sex, inclusion: { in: %w(M F),
      message: "%{value} is not a valid sex" }
    validates :color , presence: true
    validates :birth_date , presence: true
    validates :name , presence: true
    validates :sex , presence: true
    validates :description , presence: true

    has_many :cat_rental_requests, :dependent :destroy,
      primary_key: :id,
      foreign_key: :cat_id,
      class_name: :CatRentalRequest 

    def age
      now = Time.now.utc.to_date
      if birth_date
        now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
      end
    end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  validates :status, inclusion: { in: %w(APPROVED DENIED PENDING),
    message: "%{value} is not a valid status" }
  validates :cat_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, presence: true

  belongs_to :cat,  
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
        @cats = Cat.all
        # render json: cats
    end
  
  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
        
        cat = Cat.new(cat_params)

        if cat.save
            # render json: user
            redirect_to cat_url(cat)
        else
            render json: cat.errors.full_messages
        end
    end

    def edit
      @cat = Cat.find(params[:id])
    end

    def update
      cat = Cat.find(params[:id])

      if cat.update(cat_params)
        redirect_to cat_url(cat)
      else
        render json: cat.erros.full_messages, status: 422
      end
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :color, :description, :birth_date, :sex)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_cat.html.erb
<ul>
  <li>name:
    <%= cat.name %>
  </li>
  <% if action == :show %>
    <li>birth_date:
      <%= cat.birth_date %>
    </li>
    <li>age:
      <%= cat.age %>
    </li>
    <li>sex:
      <%= cat.sex %>
    </li>
    <li>color:
      <%= cat.color %>
    </li>
    <li>description:
      <%= cat.description %>
    </li>
    <table>
    <thead>
        <tr>
            <th colspan="2">Cats table</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= cat.name %></td>
            <td><%= cat.birth_date %></td>
            <td><%= cat.age %></td>
            <td><%= cat.sex %></td>
            <td><%= cat.color %></td>
            <td><%= cat.description %></td>
        </tr>
    </tbody>
</table>
    <% end %>
    <% if action == :index %>
    <a href="<%= cat_url(cat) %>">show me this cat</a>
  <% elsif action == :show %>
    <a href="<%= cats_url %>">show me ALL the cats!</a>
  <% end %>
  <br>
  <a href="<%= edit_cat_url(cat) %>">Change me!</a>
</ul>

app/views/cats/_form.html.erb
<% if type == :new %>
  <% action_url = cats_url %>
  <% button_text = "Create Cat" %>
<% elsif type == :edit %>
  <% action_url = cat_url(cat) %>
  <% button_text = "Change Cat" %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if type == :edit  %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="name">Name: </label>
  <input type="text" id="name" name="cat[name]" value="<%= cat.name %>">
  <br>
  <br>
  <label>Sex</label>
 
    <!-- note that both radio buttons have the name `cat[sex]`; that's how
         they are related -->
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M">
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F">
    <label for="cat_sex_f">Female</label>
   <br>
   <br>
   <br>
  <label for="cat_coat_color">Coat color</label>
  <select name="cat[color]" id="cat_coat_color"> 
      <option value="Black">Black</option>
      <option value="Red">Red</option>
      <option value="Blue">Blue</option>
      <option value="Green">Green</option>
      <option value="Orange">Orange</option>
   <option value="White">White</option>
   </select>
  <br>
  <br>
  <br>
  <label for="birth_date">Birth date:
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>
  <br>
  <br>
  <br>
   <label for="description">Description:
    <textarea name="cat[description]" value="<%= cat.description %>"></textarea>
  </label>
  <br><br><br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/cats/edit.html.erb
<h2>Edit Cat</h2>
<%= render 'form', cat: @cat, type: :edit %>

app/views/cats/index.html.erb
<h2>Cats</h2>
<a href="<%= new_cat_url %>">Create New Cat</a>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= render 'cat', cat: cat, action: :index %>
    </li>
    <br>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h2>Create new cat!</h2>
<%= render 'form', cat: @cat, type: :new %>

app/views/cats/show.html.erb
<%= render 'cat', cat: @cat, action: :show %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>